@url_dev=http://localhost:3055/v1/api


POST {{url_dev}}/auth/login
Content-Type: application/json

{
    "username": "admin1",
    "password": "admin123"
}

### refresh token
POST {{url_dev}}/auth/refreshtoken
Content-Type: application/json
x-client-id: 689471fc659ad34ec9a2cc6b
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk0NzFmYzY1OWFkMzRlYzlhMmNjNmIiLCJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc1NTU3MTMyOSwiZXhwIjoxNzU1NzQ0MTI5fQ.A7CnFMws8v0F7S-my5lg6msmTQgLc3SM-xFC53aYtLA