@url_dev=http://localhost:3055/v1/api

### get all inventory
GET {{url_dev}}/inventory?page=1
Content-Type: application/json
x-client-id: 689471fc659ad34ec9a2cc6b
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk0NzFmYzY1OWFkMzRlYzlhMmNjNmIiLCJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdLCJpYXQiOjE3NTU1OTQzNzAsImV4cCI6MTc1NTY4MDc3MH0.LM3DvKCKqgpxMM_0Elo0yDQac0xLetGJ8EMfn36heK8


### update stock for product

POST {{url_dev}}/inventory/update-stock/68be600612fe75e317fee0ea
Content-Type: application/json
x-client-id:68be511f453c53ec09212d3b
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGJlNTExZjQ1M2M1M2VjMDkyMTJkM2IiLCJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdLCJpYXQiOjE3NTczMDUzNDcsImV4cCI6MTc1NzM5MTc0N30.5urR5TySb6h4hhlQu8MIYjFmWXeFo2KGLP2YBCmWXvc

{
    "stock": 100
}

### find inventory by product id
GET {{url_dev}}/inventory/stock/68be600612fe75e317fee0ea
Content-Type: application/json
