@url_dev=http://localhost:3055/v1/api


### Create Product
POST {{url_dev}}/product/create-product
Content-Type: application/json
x-client-id:689471fc659ad34ec9a2cc6b
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk0NzFmYzY1OWFkMzRlYzlhMmNjNmIiLCJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdLCJpYXQiOjE3NTQ5Nzk1MzUsImV4cCI6MTc1NTA2NTkzNX0.43F2IJJZNYg4gatZP0WPmsq-b51zmDCq4nRcff_FyRw

{
    "product_name": "Jo Malone Wood Sage & Sea Salt 100ml",
    "product_thumb": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fmissi.com.vn%2Fsan-pham%2Fjo-malone-wood-sage-sea-salt%2F%3Fsrsltid%3DAfmBOor-d6qWfCxW_tJY4wlzqE_QtxrHBeI8n8D0kDdHNekwooO2CyeW&psig=AOvVaw3O9UHEL2NnRq8Q5CcuXEOy&ust=1755067499207000&source=images&cd=vfe&opi=89978449&ved=0CBUQjRxqFwoTCMCy55nWhI8DFQAAAAAdAAAAABAE",
    "product_description": "Tươi mát, thoáng đãng với muối biển và xô thơm.",
    "product_price": 2500000,
    "product_type": "Perfume",
    "product_attributes": {
      "fragrance_family": "Fresh Aromatic",
      "top_note": "Ambrette Seeds",
      "base_note": "Sea Salt",
      "concentration": "Cologne",
      "volume": 100,
      "gender": "Female",
      "longevity_hours": "4-6",
      "sillage": "Soft-Moderate",
      "launch_year": 2014
    },
    "product_categories": ["689ac94eac93b575fd97819f", "689ac94eac93b575fd97819b"],
    "product_brand": "689ac945ac93b575fd978199",
    "isDraft": true,
    "isPublished": false
  }


### update product ( bắt buộc phải truyền product_type vào )
PATCH {{url_dev}}/product/update/689add80d0ba931366487e62
Content-Type: application/json
x-client-id: 689471fc659ad34ec9a2cc6b
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk0NzFmYzY1OWFkMzRlYzlhMmNjNmIiLCJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdLCJpYXQiOjE3NTU1NzE3MzMsImV4cCI6MTc1NTY1ODEzM30.RAeR6Ar6MlYrAuwZXQBYTedKm56PWEGQRtVbqZXENJ4

{
  "product_price": 2000000,
  "product_type": "Perfume",
  "product_attributes": {
    "volume": 80
  }
}

### get products by category
GET {{url_dev}}/product/category/689ac94eac93b575fd97819b?limit=50&page=1
Content-Type: application/json


### filter product
GET {{url_dev}}/product/filter?k=orchid&page=1
Content-Type: application/json

### get all products ( published: true )
GET {{url_dev}}/product/all?page=1
Content-Type: application/json

### get product by id
GET {{url_dev}}/product/689ae2f98d25db5c08cff820
Content-Type: application/json


### get all products by brand
GET {{url_dev}}/product/brand/Dior?page=1
Content-Type: application/json

### find all product by price range
GET {{url_dev}}/product/ls-by-range?minPrice=2500000&maxPrice=3500000&page=1
Content-Type: application/json

### find related products by brand id
GET {{url_dev}}/product/related?brandId=689ae40a2fd6d6f7c96bfbeb
Content-Type: application/json

### search products by text
GET {{url_dev}}/product/search?key_search=Ocean
Content-Type: application/json

### get all products ( role admin )
GET {{url_dev}}/product/admin/all-products?page=1&limit=10
Content-Type: application/json
x-client-id: 689471fc659ad34ec9a2cc6b
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk0NzFmYzY1OWFkMzRlYzlhMmNjNmIiLCJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdLCJpYXQiOjE3NTU3NDIyMjAsImV4cCI6MTc1NTgyODYyMH0.B5iroPQWvN3WN_-ATPDtEXyGYKntF_NHYmuYcYi8Fy0

### set publish for product ( role admin )
POST {{url_dev}}/product/publish/689ae3548d25db5c08cff826
Content-Type: application/json
x-client-id: 689471fc659ad34ec9a2cc6b
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk0NzFmYzY1OWFkMzRlYzlhMmNjNmIiLCJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdLCJpYXQiOjE3NTUwNzU0MzQsImV4cCI6MTc1NTE2MTgzNH0.2s9xC8vb1EHwwPoq-ms3W97Dssg9KStiqRd6ZpwEoac

### set unpublish for product ( role admin )
POST {{url_dev}}/product/unpublish/689ae3548d25db5c08cff826
Content-Type: application/json
x-client-id: 689471fc659ad34ec9a2cc6b
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk0NzFmYzY1OWFkMzRlYzlhMmNjNmIiLCJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdLCJpYXQiOjE3NTUwNzU0MzQsImV4cCI6MTc1NTE2MTgzNH0.2s9xC8vb1EHwwPoq-ms3W97Dssg9KStiqRd6ZpwEoac


